-- AlterTable
ALTER TABLE `raport` MODIFY `agama` INTEGER NOT NULL DEFAULT 0,
    MODIFY `bahasa_indonesia` INTEGER NOT NULL DEFAULT 0,
    MODIFY `bahasa_inggris` INTEGER NOT NULL DEFAULT 0,
    MODIFY `ipa` INTEGER NOT NULL DEFAULT 0,
    MODIFY `ipk` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `ips` INTEGER NOT NULL DEFAULT 0,
    MODIFY `matematika` INTEGER NOT NULL DEFAULT 0;
